spring:
  datasource:
    url: jdbc:mysql://220.69.203.87:3306/EMR?serverTimezone=UTC
    username: jh
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

